server:
  port: 8083

spring:
  application:
    name: learning-service
  
  profiles:
    active: dev
  
  # Nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: smart-learning
        group: DEFAULT_GROUP
        cluster-name: DEFAULT
        service: ${spring.application.name}
        metadata:
          version: 1.0.0
          zone: dev
      config:
        server-addr: localhost:8848
        namespace: smart-learning
        group: DEFAULT_GROUP
        file-extension: yml
        shared-configs:
          - data-id: common-config.yml
            group: DEFAULT_GROUP
            refresh: true
        extension-configs:
          - data-id: ${spring.application.name}-${spring.profiles.active}.yml
            group: DEFAULT_GROUP
            refresh: true

  # 配置导入
  config:
    import:
      - optional:nacos:${spring.application.name}.yml
  
  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smart_learning?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: admin
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20

# MongoDB配置
spring:
  data:
    mongodb:
      uri: mongodb://admin:admin123456@localhost:27017/smart_learning?authSource=admin

# MyBatis Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# Redis配置
spring:
  redis:
    host: localhost
    port: 6379
    password: redis123456
    database: 2
    timeout: 3000ms

# 日志配置
logging:
  level:
    com.smartlearning.learning: DEBUG
    com.smartlearning.common: DEBUG
  file:
    name: logs/learning-service.log

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

# 应用信息
info:
  app:
    name: ${spring.application.name}
    description: 学习服务 - 负责学习记录、进度跟踪、笔记管理
    version: 1.0.0
