server:
  port: 8087

spring:
  application:
    name: analytics-service

  profiles:
    active: dev

  # Nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: smart-learning
        group: DEFAULT_GROUP
        cluster-name: DEFAULT
        service: ${spring.application.name}
        username: nacos
        password: nacos
        metadata:
          version: 1.0.0
          zone: dev
      config:
        server-addr: localhost:8848
        namespace: smart-learning
        group: DEFAULT_GROUP
        file-extension: yml
        username: nacos
        password: nacos
        shared-configs:
          - data-id: common-config.yml
            group: DEFAULT_GROUP
            refresh: true
        extension-configs:
          - data-id: ${spring.application.name}-${spring.profiles.active}.yml
            group: DEFAULT_GROUP
            refresh: true

  # 配置导入
  config:
    import:
      - optional:nacos:${spring.application.name}.yml
  
  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smart_learning?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: admin
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20

  # Redis配置
  redis:
    host: localhost
    port: 6379
    password: 
    database: 5
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms

  # Elasticsearch配置
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 3s
    socket-timeout: 10s

# MyBatis Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:mapper/*.xml

# 日志配置
logging:
  level:
    com.smartlearning.analytics: DEBUG
    com.smartlearning.common: DEBUG
  file:
    name: logs/analytics-service.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# 数据分析配置
analytics:
  # 数据收集配置
  collection:
    batch-size: 1000
    flush-interval: 30s
    max-queue-size: 10000
  
  # 报表生成配置
  report:
    cache-duration: 1h
    export-formats: [pdf, excel, csv]
    max-export-records: 100000
  
  # 实时分析配置
  realtime:
    window-size: 5m
    slide-interval: 1m
    watermark-delay: 10s
  
  # 数据清理配置
  cleanup:
    retention-days: 90
    cleanup-schedule: "0 2 * * *" # 每天凌晨2点执行
